"""
RafSec Utils - PDF Report Generator
=====================================
Generate professional incident reports.

Author: RafSec Team
"""

import os
from datetime import datetime
from typing import List, Dict, Optional

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


class RafSecReport(FPDF):
    """Custom PDF class with RafSec branding."""
    
    def __init__(self, logo_path: str = None):
        super().__init__()
        self.logo_path = logo_path
    
    def header(self):
        # Logo
        if self.logo_path and os.path.exists(self.logo_path):
            try:
                self.image(self.logo_path, 10, 8, 25)
            except:
                pass
        
        # Title
        self.set_font('Arial', 'B', 18)
        self.set_text_color(59, 130, 246)  # Blue
        self.cell(35)  # Move right past logo
        self.cell(0, 10, 'RafSec Incident Report', 0, 0, 'L')
        
        # Line break
        self.ln(20)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by RafSec Total Security - Page {self.page_no()}', 0, 0, 'C')


class ReportGenerator:
    """
    Generate PDF reports for security incidents.
    """
    
    def __init__(self, output_dir: str = None, logo_path: str = None):
        """
        Initialize report generator.
        
        Args:
            output_dir: Directory for saving reports
            logo_path: Path to logo image
        """
        if output_dir is None:
            output_dir = os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'reports'
            )
        
        self.output_dir = output_dir
        
        if logo_path is None:
            logo_path = os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                'assets', 'logo.png'
            )
        
        self.logo_path = logo_path if os.path.exists(logo_path) else None
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
    
    def generate_scan_report(self, scan_results: List[Dict], 
                             title: str = "Malware Scan Report") -> Optional[str]:
        """
        Generate a scan report PDF.
        
        Args:
            scan_results: List of scan result dicts
            title: Report title
            
        Returns:
            Path to generated PDF or None
        """
        if not FPDF_AVAILABLE:
            return None
        
        pdf = RafSecReport(self.logo_path)
        pdf.add_page()
        
        # Report Info Section
        pdf.set_font('Arial', 'B', 14)
        pdf.set_text_color(30, 41, 59)  # Dark
        pdf.cell(0, 10, title, 0, 1)
        
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(100, 116, 139)  # Grey
        pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
        pdf.cell(0, 6, f"Total Items: {len(scan_results)}", 0, 1)
        pdf.ln(10)
        
        # Summary
        threats = sum(1 for r in scan_results if r.get('is_threat', False))
        
        pdf.set_font('Arial', 'B', 12)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "Executive Summary", 0, 1)
        
        pdf.set_font('Arial', '', 10)
        if threats > 0:
            pdf.set_text_color(239, 68, 68)  # Red
            pdf.cell(0, 6, f"! THREATS DETECTED: {threats}", 0, 1)
        else:
            pdf.set_text_color(16, 185, 129)  # Green
            pdf.cell(0, 6, "No threats detected", 0, 1)
        
        pdf.ln(10)
        
        # Details Table
        pdf.set_font('Arial', 'B', 12)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "Scan Details", 0, 1)
        
        # Table Header
        pdf.set_font('Arial', 'B', 9)
        pdf.set_fill_color(241, 245, 249)
        pdf.cell(70, 8, "File", 1, 0, 'L', True)
        pdf.cell(40, 8, "Status", 1, 0, 'C', True)
        pdf.cell(30, 8, "Score", 1, 0, 'C', True)
        pdf.cell(50, 8, "Hash (SHA256)", 1, 1, 'L', True)
        
        # Table Rows
        pdf.set_font('Arial', '', 8)
        for result in scan_results:
            filename = result.get('filename', 'Unknown')[:35]
            status = result.get('status', 'Unknown')
            score = str(result.get('score', '-'))
            file_hash = result.get('hash', '-')[:16] + "..."
            
            # Color based on status
            if result.get('is_threat'):
                pdf.set_text_color(239, 68, 68)
            else:
                pdf.set_text_color(30, 41, 59)
            
            pdf.cell(70, 7, filename, 1, 0, 'L')
            pdf.cell(40, 7, status, 1, 0, 'C')
            pdf.cell(30, 7, score, 1, 0, 'C')
            pdf.cell(50, 7, file_hash, 1, 1, 'L')
        
        # Save
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"Scan_Report_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        try:
            pdf.output(filepath)
            return filepath
        except Exception as e:
            print(f"[ERROR] Failed to save PDF: {e}")
            return None
    
    def generate_incident_report(self, incident: Dict) -> Optional[str]:
        """
        Generate a single incident report.
        
        Args:
            incident: Dict with incident details
            
        Returns:
            Path to generated PDF or None
        """
        if not FPDF_AVAILABLE:
            return None
        
        pdf = RafSecReport(self.logo_path)
        pdf.add_page()
        
        # Title
        pdf.set_font('Arial', 'B', 16)
        pdf.set_text_color(239, 68, 68)  # Red
        pdf.cell(0, 10, "SECURITY INCIDENT REPORT", 0, 1, 'C')
        pdf.ln(10)
        
        # Incident Details
        pdf.set_font('Arial', 'B', 12)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "Incident Details", 0, 1)
        
        pdf.set_font('Arial', '', 10)
        fields = [
            ("Timestamp", incident.get('timestamp', datetime.now().isoformat())),
            ("Threat Type", incident.get('threat_type', 'Unknown')),
            ("Severity", incident.get('severity', 'Unknown')),
            ("File Path", incident.get('file_path', 'N/A')),
            ("File Hash", incident.get('hash', 'N/A')),
            ("Process", incident.get('process_name', 'N/A')),
            ("PID", str(incident.get('pid', 'N/A'))),
            ("Action Taken", incident.get('action', 'Logged')),
        ]
        
        for label, value in fields:
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(40, 7, f"{label}:", 0, 0)
            pdf.set_font('Arial', '', 10)
            pdf.cell(0, 7, str(value)[:80], 0, 1)
        
        # Save
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"Incident_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        try:
            pdf.output(filepath)
            return filepath
        except:
            return None
    
    @staticmethod
    def is_available() -> bool:
        """Check if PDF generation is available."""
        return FPDF_AVAILABLE
